name: analysis
on: [push, pull_request]

jobs:
  build:
    name: Analyze
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: "Configure for Windows with internal dependencies"
        run: cmake -DUSE_THIRDPARTY_LIBRARIES=ON -DENABLE_COMPRESSION=OFF -DENABLE_PUSH=OFF -DCMAKE_BUILD_TYPE=Debug -S ${{ github.workspace }} -B ${{ github.workspace }}/_build

      - name: Run MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action
        # Provide a unique ID to access the sarif output path
        id: run-analysis
        with:
          cmakeBuildDirectory: ${{ github.workspace }}/_build
          buildConfiguration: Debug
          # Ruleset file that will determine what checks will be run
          ruleset: NativeRecommendedRules.ruleset
